name: ClientLink
version: '${project.version}'
main: dev.misieur.ClientLink.ClientLink
api-version: 1.13
softdepend:
  - FeatherServerAPI
  - PlaceholderAPI
# packetevents
  - ProtocolLib
  - ProtocolSupport
  - ViaVersion
  - ViaBackwards
  - ViaRewind
  - Geyser-Spigot